name: npm test
on:
  workflow_dispatch:

jobs:
  run-npm-install:
    strategy:
      matrix:
        node: [ 20, lts ]
        os: [ ubuntu-latest, ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name : setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - name: run install
        shell: bash
        run: |
          npm install
          npm test